services:
  mysql:
    image: mysql:8.4.4
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_USER: kintai
      MYSQL_PASSWORD: kintai
      MYSQL_DATABASE: app
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "kintai", "-pkintai"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
